pingwit.server:
  name: "Apenko from yml"
  port: 8080

pingwit.email:
  from: mihailapenko794@gmail.com
  signature: "\n\n King regards \nPingwit"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/apenko
    username: postgres
    password: docker
  jpa:
    show-sql: true